version: '3.9'
services:
  web:
    image: c-owllook
    container_name: c-owllook-web
    ports:
     - "9010:8001"
    volumes:
     - /dokcer/owllook/web:/owllook
    depends_on:
      redis:
        condition: service_healthy
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:3.6
    container_name: c-owllook-mongo
    restart: always
    ports:
     - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 20s
    volumes:
     - /dokcer/owllook/mongodb/data/db:/data/db
     - /dokcer/owllook/mongodb/data/log:/var/log/mongodb
     - /dokcer/owllook/mongodb/data/config:/etc/mongo
    command: --config ./config/mongod.conf
  redis:
    image: redis:7.0.4
    restart: always
    container_name: c-owllook-redis
    privileged: true
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /dokcer/owllook/redis/data:/data
      - ./conf/redis.conf:/etc/redis/redis.conf
      - /dokcer/owllook/redis/logs:/logs
    command: ["redis-server", "/etc/redis/redis.conf"]